[advisories]
db-urls = ["https://github.com/RustSec/advisory-db"]
ignore = []
yanked = "deny"

[bans]
multiple-versions = "deny"
wildcards = "deny"
highlight = "all"

[licenses]
allow = ["Apache-2.0", "MIT", "Unicode-3.0"]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
